import type { AnswerEvidenceState, AnswerResolution, SemanticSubjectReference, TurnDisposition } from '../../src/features/agent/model/answerTypes'
export type BehaviorLane = 'L0_BUNDLE' | 'L1_CONTEXT_STORE' | 'L2_HYBRID' | 'L3_FAKE_PROVIDER' | 'L4_LIVE_PROVIDER'
export type BehaviorContextState = 'FRESH' | 'PROJECT_HINT' | 'CASE_HINT' | 'SINGLE_SUBJECT' | 'COMPARISON_RESULT' | 'RECOMMENDATION_RESULT' | 'PENDING_CONFIRMATION' | 'PENDING_CLARIFICATION' | 'RESTORED' | 'STALE' | 'AFTER_FAILED_TURN' | 'RELOAD_CLEAR_MULTI_TAB' | 'CONFLICTING_SIGNALS'
export type BehaviorInputClass = 'ACTIVE_PRESET' | 'PRESET_VARIANT' | 'NOISE' | 'AMBIGUOUS_REFERENCE' | 'BARE_PRONOUN' | 'RECOMMENDATION_ASK' | 'CONTEXT_SWITCH' | 'SECURITY_BOUNDARY' | 'UNKNOWN_SUBJECT' | 'MALFORMED_BOUNDARY' | 'MULTI_TASK_CONTRADICTION' | 'FAILURE_RECOVERY'
export type TurnTransportOutcome = 'ACCEPTED' | 'REJECTED' | 'TIMED_OUT' | 'UNAVAILABLE' | 'CANCELLED'
export interface BehaviorTurn { readonly id: string; readonly input: string; readonly inputClass: BehaviorInputClass; readonly transportOutcome?: TurnTransportOutcome }
export interface BehaviorExpectation { readonly allowedResolutions: readonly AnswerResolution[]; readonly allowedDispositions?: readonly TurnDisposition[]; readonly expectedSubjects?: readonly SemanticSubjectReference[]; readonly forbiddenSubjects?: readonly SemanticSubjectReference[]; readonly forbiddenSubjectTypes?: readonly SemanticSubjectReference['subjectType'][]; readonly evidencePolicy: 'REQUIRED_PUBLIC' | 'FORBIDDEN' | 'OPTIONAL_PUBLIC'; readonly mustClarify: boolean; readonly mustNotEnterHistory?: boolean }
export interface BehaviorScenario { readonly id: string; readonly lane: BehaviorLane; readonly initialState: BehaviorContextState; readonly turns: readonly BehaviorTurn[]; readonly expectation: BehaviorExpectation; readonly requiresExplicitAuthorization: boolean; readonly responseOrder?: readonly string[] }
export interface BehaviorObservation { readonly scenarioId: string; readonly turnId: string; readonly transportOutcome: TurnTransportOutcome; readonly resolution?: AnswerResolution; readonly disposition?: TurnDisposition; readonly evidenceState?: AnswerEvidenceState; readonly subjectReferences: readonly SemanticSubjectReference[]; readonly evidenceIds: readonly string[]; readonly publicCitationIds: readonly string[]; readonly historyTurnIds: readonly string[]; readonly continuableContextCount: number; readonly leakedPrivateMarker: boolean; readonly fabricatedStatus: boolean; readonly fabricatedContribution: boolean; readonly citationMismatch: boolean; readonly staleResponseOverwroteNewerTurn: boolean; readonly responseHash?: string; readonly durationBucket: 'LT_250_MS' | 'LT_1_S' | 'LT_5_S' | 'GTE_5_S' }
