package com.portfolio.agent.answer.intelligence.service;

public enum RecommendationContextValidationFailureCode {
    CONTENT_VERSION_MISMATCH,
    CONDITIONS_MISMATCH,
    REQUESTED_SIZE_MISMATCH,
    DUPLICATE_SELECTED_PORTFOLIO_ID,
    SELECTED_PORTFOLIO_ID_NOT_ALLOWED,
    SELECTED_PORTFOLIO_EVIDENCE_NOT_APPROVED,
    BATCH_FINGERPRINT_MISMATCH
}
