package com.portfolio.agent.infrastructure.model.policy;
public enum OperationReadiness { DISABLED, AVAILABLE_DETERMINISTIC, AVAILABLE_WITH_DETERMINISTIC_FALLBACK, INCOMPLETE_CONFIGURATION, PROVIDER_UNAVAILABLE }
