package com.portfolio.agent.turn.planning;

public enum GoalKind {
    PORTFOLIO_FACT,
    PORTFOLIO_COMPARE,
    PORTFOLIO_RECOMMEND,
    PORTFOLIO_REFINE_RECOMMENDATION,
    GENERAL_EXPLANATION,
    GENERAL_COMPARISON,
    APPLY_GENERAL_CONCEPT_TO_PORTFOLIO
}
