package com.portfolio.agent.answer.runtime;
public enum OperationReadiness { DISABLED, AVAILABLE_DETERMINISTIC, AVAILABLE_WITH_DETERMINISTIC_FALLBACK, INCOMPLETE_CONFIGURATION, PROVIDER_UNAVAILABLE }
