package com.portfolio.agent.answer.intelligence.retrieval;
public enum RetrievalAttemptFailure { VECTOR_UNAVAILABLE, BACKEND_CONNECTION_UNAVAILABLE, BACKEND_TIMEOUT, BUSINESS_EMPTY, EVIDENCE_INSUFFICIENT, CONTENT_VERSION_MISMATCH, INTEGRITY_FAILURE, BUDGET_EXHAUSTED }
